### PR TITLE
Retry to insert rows when an insertErrors occurs

### PR DESCRIPTION
**Pull request by yoheimuta**
In our production environment, insertErrors for timeout has occurred several times a day.

- ref. https://cloud.google.com/bigquery/docs/reference/rest/v2/tabledata/insertAll#response

```
# Excerpt of actually output log
fluentd.warn.internal.message.ip-10-0-2-89
----------------
[16:55:30] insert errors project_id="xxx" dataset="mtburnlog" table="imp" insert_errors="[#<Google::Apis::BigqueryV2::InsertAllTableDataResponse::InsertError:0x007f99694b21c0 @errors=[#<Google::Apis::BigqueryV2::ErrorProto:0x007f99694b13d8 @reason=\"timeout\">], @index=26>]"
```

Since the plugin is currently implemented to not retry the log in which insertErrors occurred, we have to resend the log manually every time.

Therefore, we added a function to resend the log where insertErrors occurred due to timeout only when the allow_retry_insert_errors option is true. Since the default for the allow_retry_insert_errors option is false, the plugin behaves as before unless an existing user makes the option true.

- ref. http://stackoverflow.com/a/25389670

### CODE REVIEW

**Comment by yoheimuta** [comment]
[memo] CI test is passed.

**Comment by joker1007** [comment]
Thanks!
I will pick up this near future.
Sorry, please wait. I am working to support fluentd v0.14.

**Comment by joker1007** [comment]
I merged to fluentd-0.12 branch, and released it as v0.4.1.

**Comment by yoheimuta** [comment]
Thanks!

**Pull request closed without merging**
