### PR TITLE
Improve placeholder

### PR DESCRIPTION
**Pull request by joker1007**
Enable to use placeholder for `project`, `dataset`, `fetch_schema_table`.

Because of it, `fetch_schema` timing is delayed.

### CODE REVIEW

**Comment by tagomoris** [comment]
It's better to check whether the values from configuration parameters use invalid placeholders or not by calling `placeholder_validate!(name, str)` in `#configure`.
That method raises configuration error if `${tag}` is used in `str` but configured buffer chunk key doesn't have `tag` (it also checks about other keys).

**Comment by joker1007** [comment]
@tagomoris Thanks!

I wanted to use `placeholder_validate!`, but I feel that current `placeholder_validate!` is not easy to use for me.
Because it is seemed that `placeholder_validate!` requires placeholder syntax in parameter.

For example in config,

```
<buffer time>
  timekey 1d
</buffer>

project yourproject_id
dataset yourdataset_id
table target_table_%Y%m%d # I want to use placeholder only table param in this config.
```

in this case, `placeholder_validate!` regards `project` and `dataset` as invalid.
The behavior is not suitable for this plugin.

Of course, I can guard `placeholder_validate!` if it is not required (ex. use regexp matching).
Is this intended usage?

**Comment by tagomoris** [comment]
@joker1007 It's intended - Once I tried to design validator API to validate combination of 2 or more configuration parameter values and configured buffer chunk keys, but I found that it's too difficult to both implement and use it.

For this case, we can validate the whole configuration and chunk keys by the code like below:

```ruby
placeholder_validate!(:project_and_database_and_table, "#{@project}/#{@database}/#{@table}")
```

It shows error message a bit difficult to understand, but it's much better than occurring problems after Fluentd starts.

**Comment by joker1007** [comment]
I understand API design. Thanks!!
the snippet is looks good to me.
I will add `placeholder_validate!`.

**Pull request merged**
