### PR TITLE
Add insert_late_timestamp option

### PR DESCRIPTION
**Pull request by paulbellamy**
I've added an option called `insert_late_timestamp <column>`. The intent is to add a column in bigquery which tracks when the record was sent to bigquery. Due to buffering, this might be very different from when the event was received by fluentd. Having both timestamps lets you track how long the events took to reach bigquery.

Happy to make changes. What do you think?

### CODE REVIEW

**Comment by joker1007** [comment]
You want to add timestamp at the timing of actual insert, is it right?
I cannot imagin the case that this feature is useful, but this is not bad to me.

I think that `insert_late_timestamp` config name is not clear.
Could you suggest other config name?

**Comment by paulbellamy** [comment]
> I think that `insert_late_timestamp` config name is not clear.

I agree, I could not immediately think of another name for it. Will give it some more thought.

**Comment by paulbellamy** [comment]
What about `add_insert_timestamp <column>`, with docs updated accordingly?

**Comment by joker1007** [comment]
Thanks!
It is looks good to me.
Would you update README?

**Comment by paulbellamy** [comment]
Readme updated and rebased for conflicts.

**Comment by joker1007** [comment]
Thanks a lot!! 😄 
I will release this feature.

**Pull request merged**
