### PR TITLE
Support a new option `watch_schema_path`

### PR DESCRIPTION
**Pull request by yoheimuta**
In our environment, since fluentd(≒ td-agent) in production can not be reloaded (because in the edge case, there is a possibility of dropping another log), every time we change the column in bigquery table, we have to replace every instances running fluentd.

If this option is supported, when schema_path is specified, it will be possible to update the schema definition without doing anything equivalent to fluentd's reload.  At least for us it is very helpful.

NOTE: The master branch that supports fluentd v0.14 can be implemented using the event_loop helper, so it is an assumption that this PR implemented for v0.12 can be rewritten more concisely.

### CODE REVIEW

**Comment by joker1007** [comment]
Thank you for pull request!

But I think that plugins should not have the responsibillity of config reload.
This is feature of fluentd-core originally.
it is better to create issue on https://github.com/fluent/fluentd about the edge case.

**Comment by yoheimuta** [comment]
Thank you for response!

I understood the point. 

In light of the fact that schema_cache_expire for fetch_schema realizes schema definition automatic updating, I thought that watch_schema_path for schema_path could be included in the responsibility of this plugin as an update function of external schema definition resources.

This function also has a useful part in the sense that it can be replaced reload of the whole td-agent which require a special care with a reload of a part of the plugin (+ ignoring error if parsing a schema file is failed) when it becomes a large-scale environment.

If it means that you should not add it, I'd like to close it, but please confirm once about the above thought 🙇

**Comment by joker1007** [comment]
I understood your thought. it is reasonable.
But, fluent-plugin-bigquery already has too many config, and so I want to take care of new feature.
Sorry, I think that fluent-plugin-bigquery should not have this feature.
By the way the purpose of `fetch_schema`  is emulation of template suffix feature (https://cloud.google.com/bigquery/streaming-data-into-bigquery) in `load` mode and schema config externalization. automatic updating is sub feature.

**Comment by yoheimuta** [comment]
Thank you very polite explanation. I was convinced. I will close it.

**Pull request closed without merging**
